"""
Django settings for iste project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&&u&$&r1%60$0erqpalplvz79uhg2r@$uc%t78fg-)!yot_$%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'nucleus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
      'django_hosts',
    'website.apps.WebsiteConfig',
   
    'api.apps.ApiConfig',
    'research.apps.ResearchConfig',
    'rest_framework',
    'rest_framework.authtoken',
      
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES']=[
        'rest_framework.renderers.JSONRenderer',
    ]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

ROOT_URLCONF = 'iste.urls'
ROOT_HOSTCONF = 'iste.hosts' 
DEFAULT_HOST='www'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,"templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nucleus.context_processors.nucleus',
            ],
        },
    },
]
NUCLEUS = {
    'sidebar':{
        'navigation':{
            'api':{
                'icon':'interview.jpg',
                #'color':'yellow',
            },
            'research':{
                'icon':'research.jpg',

            },
            'website':{
                'icon':'website.png'
            },
            'auth':{
                'icon':'auth.svg',
            }
        },

        'footer':{
            'title':'<span onclick="window.history.back()"><i title="Go Back" class="fas fa-arrow-alt-circle-left" style="font-size:50px;display: block; margin-left:auto; margin-right:auto; text-align:center;"></i> </span>'
        }
    }
}

WSGI_APPLICATION = 'iste.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'iste',
#         'USER':'root',
#         'PASSWORD':'',
#         'HOST':'127.0.0.1',
#          'PORT':'3306',
#     }
# }
PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(PROJECT_DIR, 'sqlite.db'),
    }
}

ADMIN_REORDER = (
    ('research', ('Department', 'Category', 'professor')),
    #('app2', ('App2Model1', 'App2Model2')),
)


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static'),
]

#STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.zoho.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True

EMAIL_HOST_USER='contactus@istemanipal.com'
EMAIL_HOST_PASSWORD='YBB72VkMx6HX'
DEFAULT_FROM_EMAIL='ISTE Manipal <contactus@istemanipal.com>'