# Generated by Django 3.0.5 on 2020-05-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_category_professor_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professors and Projects', 'verbose_name_plural': 'Professors and Projects'},
        ),
    ]
