# Generated by Django 3.0.5 on 2020-04-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200407_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_date',
            old_name='end_end',
            new_name='end_date',
        ),
    ]
