# Generated by Django 3.0.5 on 2020-04-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_date_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_date',
            name='name_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
