# Generated by Django 3.0.5 on 2020-05-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200410_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_date',
            options={'verbose_name': 'Dates of Events', 'verbose_name_plural': 'Dates of Events'},
        ),
    ]
