# Generated by Django 3.0.5 on 2022-03-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210522_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='github',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='board',
            name='instagram',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='linkedin',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
