# Generated by Django 3.0.5 on 2022-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20220325_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='DPs')),
                ('linkedin', models.CharField(default=None, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
