# Generated by Django 3.0.5 on 2020-05-06 17:18

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200506_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[api.models.hundred_check]),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question')},
        ),
    ]
