# Generated by Django 3.0.5 on 2020-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200506_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='brief_description',
            field=models.TextField(max_length=500),
        ),
    ]
